#!/bin/bash
#set -x verbose #echo on

workspace="$HOME/workspace"
ansible="$workspace/ansible"
  cd $ansible/hacking
  source env-setup
  ansible-vault $@ --vault-password-file ~/workspace/linux-desktop-private/vaultpass.txt
